In [4]:
import tkinter as tk
import tkinter.filedialog as fd
import pandas as pd

def choose_files():
  """Opens a dialog box to allow the user to select multiple files."""
  root = tk.Tk()
  root.withdraw()
  filenames = tk.filedialog.askopenfilenames(parent=root)
  return filenames
def read_csv_files(filenames):
  """Reads multiple CSV files into a single Pandas DataFrame.
  Args:
    filenames: A list of CSV filenames.

  Returns:
    A Pandas DataFrame containing the data from all of the input CSV files.
  """

  dfs = []
  for filename in filenames:
    df = pd.read_csv(filename)
    dfs.append(df)
  df = pd.concat(dfs)
  return df
# Choose the CSV files to read.
filenames = choose_files()
# Read the CSV files into a single Pandas DataFrame.
Data2 = read_csv_files(filenames)
# Print the DataFrame.
print(Data2)

C:\Users\45685\AppData\Local\Temp\ipykernel_13736\1496775004.py:24: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
C:\Users\45685\AppData\Local\Temp\ipykernel_13736\1496775004.py:24: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
C:\Users\45685\AppData\Local\Temp\ipykernel_13736\1496775004.py:24: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
C:\Users\45685\AppData\Local\Temp\ipykernel_13736\1496775004.py:24: DtypeWarning: Columns (10,13,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)

         airwaybill_number       dc_inscan_date  \
0             1.008256e+10  2023-09-30 09:25:53
1             1.011791e+10  2023-09-30 12:24:02
2             1.012217e+10  2023-10-01 15:44:34
3             1.012218e+10  2023-10-01 10:23:19
4             1.012544e+10                  NaN
...                    ...                  ...
1521296       7.156889e+09  2023-10-31 08:17:51
1521297       1.016484e+10  2023-10-31 08:26:20
1521298       3.249501e+09  2023-10-31 08:01:17
1521299       3.249502e+09  2023-10-31 08:03:59
1521300       3.249590e+09  2023-10-31 08:00:46

                                          shipper_name  shipper_code  \
0                FASHNEAR TECHNOLOGIES PRIVATE LIMITED        311281
1                FASHNEAR TECHNOLOGIES PRIVATE LIMITED        311281
2                FASHNEAR TECHNOLOGIES PRIVATE LIMITED        311281
3                FASHNEAR TECHNOLOGIES PRIVATE LIMITED        311281
4                FASHNEAR TECHNOLOGIES PRIVATE LIMITED        311281
...                                                ...           ...
1521296          FASHNEAR TECHNOLOGIES PRIVATE LIMITED        311281
1521297  TATA 1MG HEALTHCARE SOLUTIONS PRIVATE LIMITED        705150
1521298  TATA 1MG HEALTHCARE SOLUTIONS PRIVATE LIMITED        705150
1521299  TATA 1MG HEALTHCARE SOLUTIONS PRIVATE LIMITED        705150
1521300  TATA 1MG HEALTHCARE SOLUTIONS PRIVATE LIMITED        705150

        centre_shortcode City State_Shortcode Region_Name  OFD  DELV  ...  \
0                    BSG  BSG  Madhya Pradesh        West    1     0  ...
1                    MNG  MNG           Assam        East    1     1  ...
2                    AML  AML         Gujarat        West    0     0  ...
3                    WID  WID  Madhya Pradesh        West    1     1  ...
4                    MHD  MHD     Maharashtra        West    0     0  ...
...                  ...  ...             ...         ...  ...   ...  ...
1521296              SUY  SUR         Gujarat        West    1     1  ...
1521297              SUY  SUR         Gujarat        West    1     1  ...
1521298              SUY  SUR         Gujarat        West    1     1  ...
1521299              SUY  SUR         Gujarat        West    1     1  ...
1521300              SUY  SUR         Gujarat        West    1     1  ...

            Trip_Inscan_Time milk_run_dc dc_check final_dc  rto_cutoff_hour  \
0        2023-09-30 09:17:42         BSG     True      BSG              830
1        2023-09-30 12:10:19         MNG     True      MNG              830
2        2023-09-30 12:47:02         AML     True      AML              830
3        2023-09-30 12:10:33         WID     True      WID              830
4        2023-09-30 14:12:55         MHD    False      MHD              830
...                      ...         ...      ...      ...              ...
1521296  2023-10-31 08:17:51         SUY     True      SUY             1030
1521297  2023-10-31 08:26:20         SUY     True      SUY             1030
1521298  2023-10-31 08:01:17         SUY     True      SUY             1030
1521299  2023-10-31 08:03:59         SUY     True      SUY             1030
1521300  2023-10-31 08:00:46         SUY     True      SUY             1030

        rto_cutoff_hour_2   td                   D2                   D1  \
0                   08:30  NaN  2023-09-30 08:30:00  2023-10-01 08:30:00
1                   08:30  NaN  2023-09-30 08:30:00  2023-10-01 08:30:00
2                   08:30  NaN  2023-09-30 08:30:00  2023-10-01 08:30:00
3                   08:30  NaN  2023-09-30 08:30:00  2023-10-01 08:30:00
4                   08:30  NaN  2023-09-30 08:30:00  2023-10-01 08:30:00
...                   ...  ...                  ...                  ...
1521296             10:30  NaN  2023-10-30 10:30:00  2023-10-31 10:30:00
1521297             10:30  NaN  2023-10-30 10:30:00  2023-10-31 10:30:00
1521298             10:30  NaN  2023-10-30 10:30:00  2023-10-31 10:30:00
1521299             10:30  NaN  2023-10-30 10:30:00  2023-10-31 10:30:00
1521300             10:30  NaN  2023-10-30 10:30:00  2023-10-31 10:30:00

               check
0        NO_RTO_Lock
1        NO_RTO_Lock
2        NO_RTO_Lock
3        NO_RTO_Lock
4        NO_RTO_Lock
...              ...
1521296  NO_RTO_Lock
1521297  NO_RTO_Lock
1521298  NO_RTO_Lock
1521299  NO_RTO_Lock
1521300  NO_RTO_Lock

[49212872 rows x 25 columns]

In [5]:
Data2.shape

(49212872, 25)

In [6]:
Data2.head()

,airwaybill_number,dc_inscan_date,shipper_name,shipper_code,centre_shortcode,City,State_Shortcode,Region_Name,OFD,DELV,...,Trip_Inscan_Time,milk_run_dc,dc_check,final_dc,rto_cutoff_hour,rto_cutoff_hour_2,td,D2,D1,check
0,1.008256e+10,2023-09-30 09:25:53,FASHNEAR TECHNOLOGIES PRIVATE LIMITED,311281,BSG,BSG,Madhya Pradesh,West,1,0,...,2023-09-30 09:17:42,BSG,True,BSG,830,08:30,NaN,2023-09-30 08:30:00,2023-10-01 08:30:00,NO_RTO_Lock
1,1.011791e+10,2023-09-30 12:24:02,FASHNEAR TECHNOLOGIES PRIVATE LIMITED,311281,MNG,MNG,Assam,East,1,1,...,2023-09-30 12:10:19,MNG,True,MNG,830,08:30,NaN,2023-09-30 08:30:00,2023-10-01 08:30:00,NO_RTO_Lock
2,1.012217e+10,2023-10-01 15:44:34,FASHNEAR TECHNOLOGIES PRIVATE LIMITED,311281,AML,AML,Gujarat,West,0,0,...,2023-09-30 12:47:02,AML,True,AML,830,08:30,NaN,2023-09-30 08:30:00,2023-10-01 08:30:00,NO_RTO_Lock
3,1.012218e+10,2023-10-01 10:23:19,FASHNEAR TECHNOLOGIES PRIVATE LIMITED,311281,WID,WID,Madhya Pradesh,West,1,1,...,2023-09-30 12:10:33,WID,True,WID,830,08:30,NaN,2023-09-30 08:30:00,2023-10-01 08:30:00,NO_RTO_Lock
4,1.012544e+10,NaN,FASHNEAR TECHNOLOGIES PRIVATE LIMITED,311281,MHD,MHD,Maharashtra,West,0,0,...,2023-09-30 14:12:55,MHD,False,MHD,830,08:30,NaN,2023-09-30 08:30:00,2023-10-01 08:30:00,NO_RTO_Lock